### ISSUE TITLE
IndexError: index 3 is out of bounds for dimension 0 with size 3

### ISSUE THREAD

**Issue by liuqi8827** [tianhaowuhz/human-assisting-dex-grasp#3]
Hi,

1. I run this project successfully.
2. However, in the `Training the GraspGF` process, it shows the error: `IndexError: index 3 is out of bounds for dimension 0 with size 3`
![image](https://github.com/user-attachments/assets/f31d2391-46ef-45c7-b426-dedab1bac6b2)
3. I ran the experiment two times, but the same error occurred in each time when the time-step reached `999/50000`
![image](https://github.com/user-attachments/assets/35d5bbfc-3ed2-4502-85d8-a06df703c611)
![image](https://github.com/user-attachments/assets/318902a1-49d5-47eb-ba3d-4ff7bacb9e19)
4. The command in shell "gf_train.sh" is:
python ./Runners/TrainSDE_update.py \
--log_dir gf_pt2 \
--sde_mode vp \
--batch_size 32 \
--lr 2e-4 \
--t0 0.5 \
--train_model \
--demo_nums 15387 \
--num_envs=3 \
--demo_name=train_gf_rc \
--eval_demo_name=train_eval \
--device_id=0 \
--mode train \
--dataset_type train \
--relative \
--space riemann \
--pt_version pt2 \

**Comment by liuqi8827** [comment]
The similar error occurred when the command in shell "gf_train.sh" is:
python ./Runners/TrainSDE_update.py \
--log_dir gf_pt2 \
--sde_mode vp \
--batch_size 5077 \
--lr 2e-4 \
--t0 0.5 \
--train_model \
--demo_nums 15387 \
--num_envs=200 \
--demo_name=train_gf_rc \
--eval_demo_name=train_eval \
--device_id=0 \
--mode train \
--dataset_type train \
--relative \
--space riemann \
--pt_version pt2 \

The error shows `IndexError: index 200 is out of bounds for dimension 0 with size 200`:
![image](https://github.com/user-attachments/assets/a47d14f4-ce8b-4ac4-a048-68f41e088c2a)

**Comment by tianhaowuhz** [comment]
I think this is related to num_envs, your error index is exactly the num_envs you set, I think this is because the training data requires to open all envs, if your computer not support that, you can disable evaluation, or change the data that being used for validation.

**Comment by liuqi8827** [comment]
@tianhaowuhz I will try it today. Thanks for your reply.

**Comment by liuqi8827** [comment]
Yes. It works. Thanks a lot.
