### ISSUE TITLE
Could you please provide the link to the depth camera mount you used?可以提供一下支架的链接吗

### ISSUE THREAD

**Issue by chaos7857** [tianhaowuhz/human-assisting-dex-grasp#7]
Could you please provide the link to the depth camera mount you used?可以提供一下支架的链接吗

**Comment by tianhaowuhz** [comment]
I have set it to your email.

**Comment by chaos7857** [comment]
sorry, I forget to close it. thank you very much. It looks nice and I will start my own trial after some other preparations these days.
